### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Noobware1**

### CODE REVIEW

**Comment by ethanblake4** [comment]
For the HttpStatus class there is a much simpler and better way to bridge it; because it's an abstract class that can't be instantiated you can actually just do registry.addSource() with the original code of the class, like we do in [flutter_eval Colors](https://github.com/ethanblake4/flutter_eval/blob/master/lib/src/material/colors.dart).

**Comment by Noobware1** [comment]
> For the HttpStatus class there is a much simpler and better way to bridge it; because it's an abstract class that can't be instantiated and just has statics you can actually just do registry.addSource() with the original code of the class in a string, like we do in [flutter_eval Colors](https://github.com/ethanblake4/flutter_eval/blob/master/lib/src/material/colors.dart).

That's auto generated tho should I remove it?

**Comment by ethanblake4** [comment]
Oh, nice. I'm assuming you still had to write the __static getter functions and registerBridgeFunc() stuff yourself though no?

Either way I would say it should be replaced, yeah. It's a lot more efficient to code it as a string if possible since the compiler can tree-shake unused values, plus in this case doing so is super easy. I should add a feature to detect this in the auto generator though.

**Comment by Noobware1** [comment]
> Oh, nice. I'm assuming you still had to write the __static getter functions and registerBridgeFunc() stuff yourself though no?
> 
> Either way I would say it should be replaced, yeah. It's a lot more efficient to code it as a string if possible since the compiler can tree-shake unused values, plus in this case doing so is super easy. I should add a feature to detect this in the auto generator though.

No, I wrote a handy eval generator to help me bridge packages I needed for my project so, I used it here too.

**Comment by ethanblake4** [comment]
> No, I wrote a handy eval generator to help me bridge packages I needed for my project so, I used it here too.

That's really cool. If you're open to sharing the source I'd love to try to integrate that into dart_eval.

**Comment by ethanblake4** [comment]
Sorry for the delay on this. Please revert [this commit](https://github.com/ethanblake4/dart_eval/pull/171/commits/2e39292f4dea55a5b79e583265fb0ee42be0db15) as it is no longer necessary due to the changes I made in v0.7.6. Otherwise everything looks great now!

**Comment by Noobware1** [comment]
done

**Pull request merged**
